"""Local account manager. Python 3.11+, no third-party server dependencies."""
from __future__ import annotations

import argparse
from contextlib import closing
from datetime import datetime
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import subprocess
import threading
import time
import tomllib
import uuid
import webbrowser
import hashlib
import io
import zipfile

import migrate as m
import desktop
import history_export
import history_import
import conversation_bundle
from maintenance import Keeper

HERE = Path(__file__).resolve().parent
DEFAULT_CONFIG = b'# Generated by Codex Account Manager\nmodel_provider = "openai"\nmodel = "gpt-6-astra"\n'
FILES = ('auth.json', 'config.toml')
PROFILE_COLORS = ('#79dfbb', '#86b9e8', '#d8a0bc', '#b5a0eb', '#e4bd7b', '#76cbd1', '#e79886', '#abc97f')


def check_auth(raw):
    try:
        obj = json.loads(raw.decode('utf-8-sig'))
    except (ValueError, UnicodeError):
        raise RuntimeError('auth.json 不是有效的 UTF-8 JSON。') from None
    m.require(isinstance(obj, dict), 'auth.json 必须是 JSON 对象。')
    tokens = obj.get('tokens')
    m.require(isinstance(obj.get('OPENAI_API_KEY'), str) and obj['OPENAI_API_KEY'].strip()
              or isinstance(tokens, dict) and isinstance(tokens.get('access_token'), str)
              and tokens['access_token'].strip(), 'auth.json 缺少有效的 API Key 或登录 access_token。')
    return obj


def config_info(raw, root):
    try:
        cfg = tomllib.loads(raw.decode('utf-8-sig'))
    except (ValueError, UnicodeError):
        raise RuntimeError('config.toml 格式错误，请检查 TOML 语法。') from None
    m.require(not cfg.get('profile'), '暂不支持顶层 profile 覆盖；请将目标 provider 放在顶层配置。')
    provider = cfg.get('model_provider', 'openai')
    m.require(isinstance(provider, str) and provider, 'model_provider 必须是非空字符串。')
    m.require(provider in m.BUILTINS or provider in cfg.get('model_providers', {}),
              '找不到所选 provider 的定义。')
    return {'path': str(root / 'config.toml'), 'sha256': m.sha(raw),
            'target': provider, 'model': cfg.get('model')}


def stamp():
    return datetime.now().isoformat(timespec='seconds')


def same_account(left, right):
    if not left or not right:
        return False
    a, b = check_auth(left), check_auth(right)
    if a.get('OPENAI_API_KEY') or b.get('OPENAI_API_KEY'):
        return a.get('OPENAI_API_KEY') == b.get('OPENAI_API_KEY')
    aid = (a.get('tokens') or {}).get('account_id')
    bid = (b.get('tokens') or {}).get('account_id')
    return bool(aid and aid == bid) or a == b


def config_identity(raw):
    """Return only configuration fields that affect account switching."""
    value = tomllib.loads(raw.decode('utf-8-sig'))
    return {
        'model_provider': value.get('model_provider', 'openai'),
        'model': value.get('model'),
        'model_reasoning_effort': value.get('model_reasoning_effort'),
        'review_model': value.get('review_model'),
        'model_providers': value.get('model_providers', {}),
    }


def same_config(left, right):
    """Compare switching behavior, ignoring local UI and machine settings."""
    if not left or not right:
        return False
    try:
        return config_identity(left) == config_identity(right)
    except (ValueError, UnicodeError):
        return left == right


def config_key(raw):
    try:
        value = config_identity(raw)
        encoded = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
        return encoded
    except (ValueError, UnicodeError):
        return hashlib.sha256(raw).hexdigest()


class Manager:
    def __init__(self, root):
        self.root = Path(root).resolve()
        m.require(self.root.is_dir(), 'CODEX_HOME 不存在。')
        self.store = self.root / 'account-manager'
        m.private_folder(self.store)
        self.profiles = self.store / 'profiles'
        self.backups = self.store / 'backups'
        self.profiles.mkdir(exist_ok=True)
        self.backups.mkdir(exist_ok=True)
        for meta_path in sorted(self.profiles.glob('*/meta.json')):
            meta = m.load(meta_path)
            if not meta.get('color'):
                meta['color'] = self.next_color()
                m.save(meta_path, meta)
        self.mutex = threading.RLock()
        self.operation_lock = threading.RLock()
        self.job = {'state': 'idle', 'message': '就绪'}
        last_job = self.store / 'last-job.json'
        if last_job.exists():
            self.job = m.load(last_job)
            if self.job['state'] in ('waiting', 'running', 'closing', 'restarting'):
                self.job = {'state': 'error', 'message': '上次操作被中断，请检查备份记录和当前配置。'}
        self.cancel = threading.Event()
        self.keeper = Keeper(self)
        # Keep a recoverable snapshot even when the first page visit happens
        # before the user has chosen a display name.
        if (self.root / 'auth.json').exists():
            try:
                config = (self.root / 'config.toml').read_bytes() if (self.root / 'config.toml').exists() else None
                self.create('未命名配置', (self.root / 'auth.json').read_bytes(), config)
            except (RuntimeError, OSError):
                pass

    def profile_dir(self, pid):
        m.require(isinstance(pid, str) and re.fullmatch(r'[a-f0-9]{32}', pid), '无效的配置 ID。')
        path = self.profiles / pid
        m.require(path.is_dir(), '账号配置不存在。')
        return path

    def read_profile(self, pid):
        path = self.profile_dir(pid)
        auth = (path / 'auth.json').read_bytes()
        check_auth(auth)
        config = (path / 'config.toml').read_bytes() if (path / 'config.toml').exists() else DEFAULT_CONFIG
        return m.load(path / 'meta.json'), auth, config, config_info(config, self.root)

    def active_id(self):
        path = self.store / 'active.json'
        return m.load(path).get('id') if path.exists() else None

    def running_job(self):
        return self.job['state'] in ('waiting', 'running', 'closing', 'restarting')

    def ensure_ready(self):
        m.require(not self.running_job(), '有操作正在执行，请等待完成。')
        m.require(not self.keeper.running, '正在维护登录凭据，请稍后再试。')
        m.require(not self.pending(), '存在未完成的切换，请先从备份恢复。')
        m.require(not history_import.pending(self.store), '存在未完成的对话导入，请到对话迁移模块恢复。')

    def pending(self):
        return [p for p in self.backups.glob('*/manifest.json')
                if m.load(p)['state'] in ('prepared', 'recovery_required')]

    def create(self, name, auth, config=None):
        self.ensure_ready()
        m.require(isinstance(name, str) and 0 < len(name.strip()) <= 80, '请输入 1–80 字的账号名称。')
        check_auth(auth)
        config_info(config if config is not None else DEFAULT_CONFIG, self.root)
        for existing in self.profiles.iterdir():
            _, existing_auth, existing_cfg, _ = self.read_profile(existing.name)
            candidate_cfg = config if config is not None else DEFAULT_CONFIG
            if same_account(auth, existing_auth) and same_config(candidate_cfg, existing_cfg):
                requested = name.strip()
                meta_path = existing / 'meta.json'
                meta = m.load(meta_path)
                if requested and meta.get('name') in ('默认配置', '未命名配置') and requested not in ('默认配置', '未命名配置'):
                    meta['name'] = requested
                    m.save(meta_path, meta)
                return {'id': existing.name}
        pid = uuid.uuid4().hex
        path = self.profiles / pid
        path.mkdir()
        m.atomic(path / 'auth.json', auth)
        if config is not None:
            m.atomic(path / 'config.toml', config)
        m.save(path / 'meta.json', {'id': pid, 'name': name.strip(), 'created': stamp(), 'color': self.next_color()})
        return {'id': pid}

    def candidates(self):
        items = []
        for path in sorted(self.root.glob('auth*.json')):
            if path.name == 'auth.json':
                continue
            suffix = path.stem[4:]
            if not suffix or suffix[0] not in ('_', '-', '.'):
                continue
            cfg = self.root / ('config' + suffix + '.toml')
            items.append({'key': path.name, 'name': suffix[1:], 'auth': path.name,
                          'config': cfg.name if cfg.is_file() else None})
        return items

    def import_candidate(self, key):
        item = next((x for x in self.candidates() if x['key'] == key), None)
        m.require(item is not None, '没有找到对应的本机文件。')
        config = (self.root / item['config']).read_bytes() if item['config'] else None
        return self.create(item['name'], (self.root / item['auth']).read_bytes(), config)

    def delete(self, pid):
        self.ensure_ready()
        m.require(pid != self.active_id(), '不能删除当前正在使用的账号，请先切换到其他账号。')
        path = self.profile_dir(pid)
        meta = m.load(path / 'meta.json')
        shutil.rmtree(path)
        return {'ok': True, 'name': meta.get('name', pid)}

    def state(self):
        with self.mutex:
            profiles = []
            active = self.active_id()
            live_auth = (self.root / 'auth.json').read_bytes() if (self.root / 'auth.json').exists() else None
            live_cfg = (self.root / 'config.toml').read_bytes() if (self.root / 'config.toml').exists() else None
            comparable_live_cfg = live_cfg or DEFAULT_CONFIG
            for path in sorted(self.profiles.iterdir()):
                meta, auth, config, cfg = self.read_profile(path.name)
                profiles.append({**meta, '_key': (check_auth(auth).get('OPENAI_API_KEY') or (check_auth(auth).get('tokens') or {}).get('account_id') or m.sha(auth), config_key(config)),
                                 'provider': cfg['target'], 'model': cfg['model'],
                                 'auto_config': not (path / 'config.toml').exists(),
                                 'active': path.name == active and same_config(config, comparable_live_cfg),
                                 'matches': same_config(config, comparable_live_cfg) and same_account(auth, live_auth),
                                 'auth_type': 'API Key' if check_auth(auth).get('OPENAI_API_KEY') else 'ChatGPT'})
            current = {'provider': 'openai', 'model': None, 'has_auth': live_auth is not None,
                       'has_config': live_cfg is not None, 'saved': False, 'save_name': None,
                       'unsaved': bool(live_auth), 'first_use': not any(p['name'] not in ('默认配置', '未命名配置') for p in profiles)}
            try:
                if live_cfg is not None:
                    cfg = config_info(live_cfg, self.root)
                    current.update(provider=cfg['target'], model=cfg['model'])
                else:
                    cfg = config_info(DEFAULT_CONFIG, self.root)
                    current.update(provider=cfg['target'], model=cfg['model'])
            except RuntimeError as exc:
                current['error'] = str(exc)
            visible = []
            seen = set()
            for profile in profiles:
                key = profile.pop('_key')
                if profile['name'] in ('默认配置', '未命名配置') or key in seen:
                    continue
                seen.add(key)
                visible.append(profile)
            for profile in profiles:
                if profile['matches'] and profile['name'] not in ('默认配置', '未命名配置'):
                    current.update(saved=True, save_name=profile['name'], unsaved=False)
                    break
            if not current['saved'] and active:
                selected = next((p for p in profiles if p['id'] == active and p['name'] not in ('默认配置', '未命名配置') and p['active']), None)
                if selected:
                    current.update(saved=True, save_name=selected['name'], unsaved=False)
            backups = []
            for path in sorted(self.backups.glob('*/manifest.json'), reverse=True):
                obj = m.load(path)
                backups.append({k: obj.get(k) for k in ('id', 'created', 'name', 'state', 'count')})
            return {'home': str(self.root), 'current': current, 'profiles': visible,
                    'candidates': self.candidates(), 'backups': backups, 'job': self.job.copy(),
                    'recovery_required': bool(self.pending()), 'import_recovery_required': bool(history_import.pending(self.store)), 'maintenance': self.keeper.public()}

    def export_profiles(self, pid=None):
        self.ensure_ready()
        profiles = self.state()['profiles']
        if pid is not None:
            self.profile_dir(pid)
            profiles = [profile for profile in profiles if profile['id'] == pid]
            m.require(profiles, '该账号不在已保存账号列表中。')
        m.require(profiles, '暂无已保存账号可导出，请先保存当前配置。')
        with self.operation_lock:
            output = io.BytesIO()
            index = []
            with zipfile.ZipFile(output, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
                for profile in profiles:
                    pid = profile['id']
                    path = self.profile_dir(pid)
                    meta, auth, _, _ = self.read_profile(pid)
                    # Prefix and full ID keep names portable, unique and inside the archive.
                    label = re.sub(r'[^\w\-]', '_', meta['name'], flags=re.UNICODE)[:40]
                    folder = f'accounts/account-{label}-{pid}'
                    archive.writestr(folder + '/auth.json', auth)
                    has_config = (path / 'config.toml').exists()
                    if has_config:
                        archive.writestr(folder + '/config.toml', (path / 'config.toml').read_bytes())
                    entry = {'name': meta['name'], 'color': meta.get('color'),
                             'folder': folder, 'auto_config': not has_config}
                    archive.writestr(folder + '/account.json', json.dumps(entry, ensure_ascii=False, indent=2))
                    index.append(entry)
                archive.writestr('accounts.json', json.dumps({'version': 1, 'created': stamp(), 'accounts': index}, ensure_ascii=False, indent=2))
                archive.writestr('README.txt', 'Codex Account Manager 账号配置导出\n\n此压缩包含明文登录凭据，请妥善保管，不要公开分享。\n每个账号位于 accounts 下的独立目录；account.json 记录原名称和颜色。\n在另一台电脑解压后，点击“添加账号”，填写原名称并选择该目录内的 auth.json 和 config.toml。只有 auth.json 时不要选择 config 文件。颜色可点击图标重新设置。\n仅导出账号列表中的已保存副本，不含历史备份、对话、未命名快照或未导入文件，也不自动同步当前运行中的凭据。\n')
            return output.getvalue()

    def export_to_directory(self, directory, pid=None):
        m.require(isinstance(directory, str) and directory.strip(), '请输入完整文件夹路径。')
        folder = Path(directory).expanduser()
        m.require(folder.is_absolute() and folder.is_dir(), '请选择本机已存在的文件夹，使用完整路径。')
        folder = folder.resolve()
        raw = self.export_profiles(pid)
        label = ''
        if pid is not None:
            meta = m.load(self.profile_dir(pid) / 'meta.json')
            label = re.sub(r'[^\w\-]', '_', meta['name'])[:40] + '-'
        target = folder / ('Codex-Accounts-' + label + datetime.now().strftime('%Y%m%d-%H%M%S') + '-' + uuid.uuid4().hex[:8] + '.zip')
        fd = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        try:
            with os.fdopen(fd, 'wb') as stream:
                stream.write(raw)
        except Exception:
            target.unlink(missing_ok=True)
            raise
        return {'ok': True, 'path': str(target)}

    def next_color(self):
        colors = [m.load(p).get('color') for p in self.profiles.glob('*/meta.json')]
        return min(PROFILE_COLORS, key=colors.count)

    def set_color(self, pid, color):
        self.ensure_ready()
        m.require(isinstance(color, str) and re.fullmatch(r'#[0-9a-fA-F]{6}', color), '无效颜色。')
        path = self.profile_dir(pid) / 'meta.json'
        meta = m.load(path)
        meta['color'] = color
        m.save(path, meta)
        return {'ok': True}

    def details(self, pid):
        meta, auth, config, _ = self.read_profile(pid)
        path = self.profile_dir(pid)
        return {'id': pid, 'name': meta['name'], 'color': meta.get('color', '#79dfbb'),
                'directory': str(path), 'auth_path': str(path / 'auth.json'),
                'config_path': str(path / 'config.toml'), 'auth': auth.decode('utf-8-sig'),
                'config': config.decode('utf-8-sig') if (path / 'config.toml').exists() else '',
                'revision': m.sha(auth + b'\0' + ((path / 'config.toml').read_bytes() if (path / 'config.toml').exists() else b''))}

    def edit(self, data):
        self.ensure_ready()
        pid = data.get('id')
        previous = self.details(pid)
        m.require(data.get('revision') == previous['revision'], '文件已被其他操作更新，请关闭后重新打开编辑。')
        auth = data.get('auth', '').encode('utf-8')
        config = data.get('config', '').encode('utf-8')
        check_auth(auth)
        if config.strip():
            config_info(config, self.root)
        path = self.profile_dir(pid)
        meta = m.load(path / 'meta.json')
        revision = self.store / 'profile-revisions' / pid / (datetime.now().strftime('%Y%m%d-%H%M%S') + '-' + uuid.uuid4().hex[:8])
        revision.mkdir(parents=True)
        for name in (*FILES, 'meta.json'):
            if (path / name).exists():
                m.atomic(revision / name, (path / name).read_bytes())
        try:
            m.atomic(path / 'auth.json', auth)
            if config.strip():
                m.atomic(path / 'config.toml', config)
            else:
                (path / 'config.toml').unlink(missing_ok=True)
            meta.update(edited_auth=meta.get('edited_auth', False) or auth != (revision / 'auth.json').read_bytes())
            m.save(path / 'meta.json', meta)
        except Exception:
            for name in (*FILES, 'meta.json'):
                if (revision / name).exists():
                    m.atomic(path / name, (revision / name).read_bytes())
                else:
                    (path / name).unlink(missing_ok=True)
            raise
        return self.details(pid)

    def reveal(self, pid):
        path = self.profile_dir(pid)
        self.read_profile(pid)
        if os.name == 'nt':
            os.startfile(str(path))
        else:
            import sys
            subprocess.Popen(['open' if sys.platform == 'darwin' else 'xdg-open', str(path)],
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return {'ok': True}

    def plan(self, pid, archived=False):
        _, _, _, cfg = self.read_profile(pid)
        if not list(self.root.glob('state_*.sqlite')):
            return {'version': m.VERSION, 'config': cfg, 'records': []}
        return m.make_plan(self.root, archived=archived, config=cfg)

    def preview(self, pid, archived=False):
        plan = self.plan(pid, archived)
        return {'provider': plan['config']['target'], 'count': len(plan['records']),
                'records': [{'title': r['title'], 'source': r['source']} for r in plan['records'][:100]]}

    def backup(self, name):
        bid = datetime.now().strftime('%Y%m%d-%H%M%S') + '-' + uuid.uuid4().hex[:8]
        path = self.backups / bid
        path.mkdir()
        present = []
        for filename in FILES:
            source = self.root / filename
            if source.exists():
                m.atomic(path / filename, source.read_bytes())
                present.append(filename)
        manifest = {'id': bid, 'name': name, 'created': stamp(), 'state': 'prepared',
                    'present': present, 'previous_active': self.active_id(), 'migration': None, 'count': 0}
        m.save(path / 'manifest.json', manifest)
        return path, manifest

    def restore_files(self, path, manifest):
        for filename in FILES:
            if filename in manifest['present']:
                m.atomic(self.root / filename, (path / filename).read_bytes())
            else:
                (self.root / filename).unlink(missing_ok=True)
        m.save(self.store / 'active.json', {'id': manifest['previous_active']})

    def switch(self, pid, archived=False, guard=m.idle):
        m.require(not self.pending(), '存在未完成的切换，请先从备份恢复。')
        guard()
        self.keeper.replay_rotation()
        meta, auth, config, _ = self.read_profile(pid)
        profile_config = self.profile_dir(pid) / 'config.toml'
        has_profile_config = profile_config.exists()
        guard()
        plan = self.plan(pid, archived)
        # Preserve refreshed credentials only when the selected account still matches.
        active = self.active_id()
        if active:
            old_path = self.profile_dir(active)
            live = self.root / 'auth.json'
            if live.exists():
                old = check_auth((old_path / 'auth.json').read_bytes())
                new = check_auth(live.read_bytes())
                old_id = (old.get('tokens') or {}).get('account_id')
                new_id = (new.get('tokens') or {}).get('account_id')
                if not m.load(old_path / 'meta.json').get('edited_auth') and (old == new or old_id and old_id == new_id):
                    m.atomic(old_path / 'auth.json', live.read_bytes())
                    if active == pid:
                        auth = live.read_bytes()
        path, manifest = self.backup(meta['name'])
        manifest['count'] = len(plan['records'])

        def on_backup(backup):
            manifest['migration'] = str(backup)
            m.save(path / 'manifest.json', manifest)

        try:
            guard()
            for filename in FILES:
                (self.root / filename).unlink(missing_ok=True)
            m.atomic(self.root / 'auth.json', auth)
            if has_profile_config:
                m.atomic(self.root / 'config.toml', config)
            else:
                m.atomic(self.root / 'config.toml', DEFAULT_CONFIG)
            if plan['records']:
                m.apply_plan(plan, guard=guard, on_backup=on_backup)
            m.save(self.store / 'active.json', {'id': pid})
            meta.pop('edited_auth', None)
            m.save(self.profile_dir(pid) / 'meta.json', meta)
            manifest.update(state='applied', after={f: m.sha((self.root / f).read_bytes()) for f in FILES if (self.root / f).exists()})
            m.save(path / 'manifest.json', manifest)
            return {'backup': path.name, 'count': len(plan['records'])}
        except Exception:
            try:
                guard()
                if manifest['migration']:
                    m.rollback(manifest['migration'], guard=guard)
                self.restore_files(path, manifest)
                manifest['state'] = 'reverted'
            except Exception:
                manifest['state'] = 'recovery_required'
            m.save(path / 'manifest.json', manifest)
            raise

    def delete_backups(self, ids):
        self.ensure_ready()
        m.require(isinstance(ids, list) and ids and len(ids) <= 10000, '请选择要删除的备份（最多 10000 条）。')
        m.require(all(isinstance(bid, str) and re.fullmatch(r'\d{8}-\d{6}-[a-f0-9]{8}', bid) for bid in ids), '无效备份 ID。')
        ids = list(dict.fromkeys(ids))

        def safe_directory(path, parent):
            m.require(path.resolve().parent == parent.resolve(), '备份路径不在指定目录内，已停止删除。')
            if path.exists():
                m.require(path.is_dir(), '备份路径不是目录。')
                for entry in [path, *path.rglob('*')]:
                    m.require(not entry.is_symlink() and not getattr(entry, 'is_junction', lambda: False)(),
                              '备份包含链接，已停止删除。')

        with self.operation_lock, m.lock(self.root):
            manifests = {p.parent.name: m.load(p) for p in self.backups.glob('*/manifest.json')}
            targets = []
            for bid in ids:
                obj = manifests.get(bid)
                m.require(obj and obj.get('state') in ('applied', 'reverted'), '备份不存在或仍需恢复，不能删除。')
                path = self.backups / bid
                safe_directory(path, self.backups)
                linked = Path(obj['migration']) if obj.get('migration') else None
                if linked:
                    safe_directory(linked, self.root / 'provider-migration-backups')
                    m.require(not any(other != bid and record.get('migration') and Path(record['migration']).resolve() == linked.resolve()
                                      for other, record in manifests.items()), '迁移备份被其他记录引用，不能删除。')
                targets.append((bid, path, linked))
            deleted, failed = [], []
            for bid, path, linked in targets:
                try:
                    if linked and linked.exists():
                        shutil.rmtree(linked)
                    shutil.rmtree(path)
                    deleted.append(bid)
                except OSError:
                    failed.append(bid)
            return {'deleted': deleted, 'failed': failed}

    def restore(self, bid, guard=m.idle):
        m.require(isinstance(bid, str) and re.fullmatch(r'\d{8}-\d{6}-[a-f0-9]{8}', bid), '无效备份 ID。')
        path = self.backups / bid
        manifest = m.load(path / 'manifest.json')
        m.require(manifest['state'] in ('applied', 'prepared', 'recovery_required'), '该备份已恢复。')
        restorable = sorted(p.parent.name for p in self.backups.glob('*/manifest.json')
                            if m.load(p)['state'] in ('applied', 'prepared', 'recovery_required'))
        m.require(restorable and bid == restorable[-1], '请先恢复最近一次切换，避免覆盖后续更改。')
        guard()
        if manifest['state'] == 'applied':
            for f, expected in manifest['after'].items():
                live = self.root / f
                m.require(live.exists() and m.sha(live.read_bytes()) == expected,
                          '当前配置或登录凭据已变化，请使用账号切换，避免覆盖新状态。')
        if manifest['migration']:
            migration = Path(manifest['migration'])
            if m.load(migration / 'manifest.json')['state'] != 'rolled_back':
                m.rollback(migration, guard=guard)
        manifest['state'] = 'recovery_required'
        m.save(path / 'manifest.json', manifest)
        guard()
        self.restore_files(path, manifest)
        manifest['state'] = 'reverted'
        m.save(path / 'manifest.json', manifest)

    def start_job(self, action, payload):
        with self.mutex:
            m.require(not self.running_job(), '有操作正在执行。')
            m.require(not self.keeper.running, '正在维护登录凭据，请稍后再试。')
            if action in ('switch', 'update'):
                self.ensure_ready()
                self.read_profile(payload.get('id'))
            elif action == 'import-conversations':
                self.ensure_ready()
                history_import.merge(self.root, self.store, self.import_path(payload.get('token')),
                                     payload.get('ids'), payload.get('cwd', ''), dry_run=True, destination=payload.get('destination', ''))
            self.cancel.clear()
            self.job = {'state': 'waiting', 'message': '等待 Codex 完全退出，尚未修改文件。'}
            restart = payload.get('restart', True)

        def run():
            switched = False
            try:
                if restart:
                    appid = self.resolve_app()
                    with self.mutex:
                        self.job = {'state': 'closing', 'message': '正在退出 Codex，完成切换后会自动重启。'}
                        m.save(self.store / 'last-job.json', self.job)
                    if not desktop.close_desktop(self.cancel):
                        self.job = {'state': 'cancelled', 'message': '已取消；未修改配置，可手动重新打开 Codex。'}
                        return
                deadline = time.monotonic() + 3600
                while m.busy():
                    m.require(time.monotonic() < deadline, '等待超时，未开始修改文件。')
                    if self.cancel.wait(2):
                        with self.mutex:
                            self.job = {'state': 'cancelled', 'message': '已取消，未修改文件。'}
                        return
                with self.mutex:
                    if self.cancel.is_set():
                        self.job = {'state': 'cancelled', 'message': '已取消，未修改文件。'}
                        return
                    self.job = {'state': 'running', 'message': '正在备份、切换配置并同步 provider，请勿启动 Codex。'}
                with self.operation_lock, m.lock(self.root):
                    m.idle()
                    if action in ('switch', 'update'):
                        result = self.switch(payload['id'], bool(payload.get('archived')))
                        message = f'切换完成，已迁移 {result["count"]} 个对话。可以启动 Codex。'
                    elif action == 'recover-conversations':
                        history_import.recover(self.root, self.store)
                        message = '已核对并恢复中断的对话导入。可以启动 Codex。'
                    elif action == 'import-conversations':
                        package = self.import_path(payload['token'])
                        result = history_import.merge(self.root, self.store, package, payload['ids'], payload.get('cwd', ''), destination=payload.get('destination', ''))
                        message = f'已导入 {result["count"]} 条对话和 {result.get("files", 0)} 个文件，跳过 {result["skipped"]} 条已有对话。可以启动 Codex。'
                        package.unlink(missing_ok=True)
                    else:
                        self.restore(payload['id'])
                        message = '已恢复切换前的配置和 provider。可以启动 Codex。'
                    switched = True
                if restart:
                    with self.mutex:
                        self.job = {'state': 'restarting', 'message': '配置已切换，正在重新启动 Codex。'}
                    self.launch(appid=appid, internal=True)
                    message = message.replace('可以启动 Codex。', '已重新启动 Codex。')
                with self.mutex:
                    self.job = {'state': 'done', 'message': message}
            except Exception as exc:
                with self.mutex:
                    self.job = {'state': 'error', 'message': ('配置操作已完成，但自动重启失败，可手动启动 Codex。' if switched else '') + str(exc)}
            finally:
                m.save(self.store / 'last-job.json', self.job)

        threading.Thread(target=run, daemon=True).start()
        return {'ok': True}

    def import_path(self, token):
        m.require(isinstance(token, str) and re.fullmatch(r'[a-f0-9]{32}', token), '无效导入任务。')
        path = self.store / 'conversation-import-staging' / (token + '.zip')
        m.require(path.is_file() and not path.is_symlink() and time.time() - path.stat().st_mtime < 86400, '导入文件已过期，请重新选择 ZIP。')
        return path

    def resolve_app(self):
        if os.name != 'nt':
            return desktop.resolve_posix()
        # Resolve the installed desktop app before making any config changes.
        command = ("$p = Get-AppxPackage -Name 'OpenAI.Codex' | Select-Object -First 1; "
                   "if ($p) { $a = (Get-AppxPackageManifest -Package $p.PackageFullName).Package.Applications.Application "
                   "| Where-Object { $_.Executable -match 'ChatGPT.exe$|Codex.exe$' } | Select-Object -First 1; "
                   "if ($a) { $p.PackageFamilyName + '!' + $a.Id } } else { "
                   "Get-StartApps | Where-Object { $_.Name -eq 'Codex' } | Select-Object -ExpandProperty AppID -First 1 }")
        result = subprocess.run(['powershell.exe', '-NoProfile', '-NonInteractive', '-Command', command],
                                capture_output=True, text=True, check=True, creationflags=subprocess.CREATE_NO_WINDOW)
        appid = result.stdout.strip()
        m.require(appid and re.fullmatch(r'[A-Za-z0-9._!\-]+', appid), '未找到 Codex 桌面端入口，请手动打开 Codex。')
        return appid

    def launch(self, appid=None, internal=False):
        if not internal:
            self.ensure_ready()
        appid = appid or self.resolve_app()
        m.require(self.operation_lock.acquire(blocking=False), '正在维护配置，请稍后重试启动。')
        try:
            with m.lock(self.root):
                m.idle()
                config = self.root / 'config.toml'
                if not config.exists():
                    check_auth((self.root / 'auth.json').read_bytes())
                    m.atomic(config, DEFAULT_CONFIG)
                config_info(config.read_bytes(), self.root)
                if os.name == 'nt':
                    subprocess.Popen(['explorer.exe', 'shell:AppsFolder\\' + appid])
                else:
                    subprocess.Popen(appid, start_new_session=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        finally:
            self.operation_lock.release()
        if internal:
            deadline = time.monotonic() + 20
            while time.monotonic() < deadline:
                if m.busy():
                    return {'ok': True}
                time.sleep(1)
            raise RuntimeError('未检测到 Codex 启动。')
        return {'ok': True}


class Handler(BaseHTTPRequestHandler):
    server_version = 'CodexAccounts/1.0'

    def log_message(self, fmt, *args):
        pass

    def send(self, code, data, mime='application/json; charset=utf-8'):
        raw = json.dumps(data, ensure_ascii=False).encode('utf-8') if not isinstance(data, bytes) else data
        self.send_response(code)
        self.send_header('Content-Type', mime)
        self.send_header('Content-Length', str(len(raw)))
        self.send_header('Cache-Control', 'no-store')
        self.send_header('X-Content-Type-Options', 'nosniff')
        self.send_header('Referrer-Policy', 'no-referrer')
        self.send_header('Content-Security-Policy', "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'")
        self.end_headers()
        self.wfile.write(raw)

    def valid_host(self):
        return self.headers.get('Host') == f'127.0.0.1:{self.server.server_port}'

    def send_archive(self, path):
        self.send_response(200)
        self.send_header('Content-Type', 'application/zip')
        self.send_header('Content-Length', str(path.stat().st_size))
        self.send_header('Cache-Control', 'no-store')
        self.send_header('X-Content-Type-Options', 'nosniff')
        self.end_headers()
        with path.open('rb') as stream:
            shutil.copyfileobj(stream, self.wfile, 1024 * 1024)

    def do_GET(self):
        if not self.valid_host():
            return self.send(403, {'error': 'Invalid host'})
        try:
            if self.path == '/health':
                return self.send(200, {'service': 'codex-account-manager', 'instance': self.server.instance})
            if self.path == '/api/state':
                m.require(self.headers.get('X-CSRF-Token') == self.server.token, '请求验证失败，请刷新页面。')
                return self.send(200, self.server.manager.state())
            assets = {'/': ('index.html', 'text/html; charset=utf-8'),
                      '/account-manager.svg': ('account-manager.svg', 'image/svg+xml'),
                      '/app.js': ('app.js', 'text/javascript; charset=utf-8'),
                      '/style.css': ('style.css', 'text/css; charset=utf-8'),
                      '/tech.css': ('tech.css', 'text/css; charset=utf-8'),
                      '/lucide.js': ('lucide.js', 'text/javascript; charset=utf-8')}
            if self.path not in assets:
                return self.send(404, {'error': 'Not found'})
            filename, mime = assets[self.path]
            raw = (HERE / 'ui' / filename).read_bytes()
            if filename == 'index.html':
                raw = raw.replace(b'__CSRF_TOKEN__', self.server.token.encode())
            self.send(200, raw, mime)
        except Exception:
            self.send(400, {'error': '读取失败，请检查本机配置文件或刷新页面。'})

    def do_POST(self):
        origin = f'http://127.0.0.1:{self.server.server_port}'
        if (not self.valid_host() or self.headers.get('Origin') != origin
                or self.headers.get('X-CSRF-Token') != self.server.token
                or self.headers.get('Content-Type', '').split(';')[0] != ('application/zip' if self.path == '/api/conversations/upload' else 'application/json')):
            return self.send(403, {'error': '请求来源验证失败。'})
        try:
            length = int(self.headers.get('Content-Length', '0'))
            if self.path == '/api/conversations/upload':
                m.require(0 < length <= history_import.MAX_UPLOAD, 'ZIP 最大支持 8 GB，请分批导入。')
                manager = self.server.manager
                with manager.mutex:
                    manager.ensure_ready()
                    folder = manager.store / 'conversation-import-staging'
                    folder.mkdir(exist_ok=True)
                    for old in folder.glob('*.zip'):
                        if re.fullmatch(r'[a-f0-9]{32}\.zip', old.name) and time.time() - old.stat().st_mtime >= 86400:
                            old.unlink()
                    token = uuid.uuid4().hex
                    path = folder / (token + '.zip')
                    try:
                        with path.open('xb') as output:
                            remaining = length
                            while remaining:
                                chunk = self.rfile.read(min(1024 * 1024, remaining))
                                m.require(chunk, '上传中断，请重新选择文件。')
                                output.write(chunk)
                                remaining -= len(chunk)
                        records = history_import.preview(manager.root, path)
                    except Exception:
                        path.unlink(missing_ok=True)
                        raise
                return self.send(200, {'token': token, 'records': records})
            m.require(0 < length <= 2_000_000, '请求文件过大或为空。')
            data = json.loads(self.rfile.read(length))
            m.require(isinstance(data, dict), '无效请求。')
            manager = self.server.manager
            with manager.mutex:
                if self.path == '/api/conversations/import':
                    result = manager.start_job('import-conversations', data)
                elif self.path == '/api/conversations/recover':
                    result = manager.start_job('recover-conversations', data)
                elif self.path == '/api/conversations/discard':
                    manager.ensure_ready()
                    manager.import_path(data.get('token')).unlink()
                    result = {'ok': True}
                elif self.path == '/api/conversations':
                    catalog = history_export.catalog(manager.root)
                    result = {'records': catalog['records'], 'warnings': catalog['warnings'],
                              'projects': conversation_bundle.project_list(manager.root, catalog['records'])}
                elif self.path == '/api/conversations/export-preview':
                    catalog = history_export.catalog(manager.root)
                    selected = catalog['records']
                    if data.get('mode') != 'all':
                        m.require(isinstance(data.get('ids'), list) and data['ids'], '请选择对话或项目。')
                        selected = [r for r in selected if r['id'] in data['ids']]
                    result = conversation_bundle.collect(manager.root, selected, data.get('project_ids'), data.get('extra_paths'))
                    result = {k: v for k, v in result.items() if k != 'metadata'}
                elif self.path == '/api/conversations/export':
                    manager.ensure_ready()
                    m.require(data.get('mode') in ('all', 'selected'), '请选择导出范围。')
                    ids = None if data['mode'] == 'all' else data.get('ids')
                    if data['mode'] == 'selected':
                        m.require(isinstance(ids, list) and ids, '请选择要导出的对话。')
                    folder = None
                    if 'directory' in data:
                        m.require(isinstance(data['directory'], str) and data['directory'].strip(), '请输入完整文件夹路径。')
                        folder = Path(data['directory']).expanduser()
                        m.require(folder.is_absolute() and folder.is_dir(), '请选择本机已存在的文件夹，使用完整路径。')
                        folder = folder.resolve()
                    with manager.operation_lock, history_export.archive_history(manager.root, manager.store, ids, data.get('project_ids'), data.get('extra_paths')) as (archive, manifest):
                        if folder is None:
                            return self.send_archive(archive)
                        target = folder / ('Codex-Conversations-' + datetime.now().strftime('%Y%m%d-%H%M%S') + '-' + uuid.uuid4().hex[:8] + '.zip')
                        fd = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
                        try:
                            with os.fdopen(fd, 'wb') as output, archive.open('rb') as source:
                                shutil.copyfileobj(source, output, 1024 * 1024)
                        except Exception:
                            target.unlink(missing_ok=True)
                            raise
                        result = {'ok': True, 'path': str(target), 'count': len(manifest['records']), 'warnings': manifest['warnings']}
                elif self.path == '/api/export':
                    if 'directory' in data:
                        return self.send(200, manager.export_to_directory(data['directory'], data.get('id')))
                    return self.send(200, manager.export_profiles(data.get('id')), 'application/zip')
                elif self.path == '/api/import':
                    result = manager.create(data.get('name'), data.get('auth', '').encode('utf-8'),
                                            data['config'].encode('utf-8') if data.get('config') is not None else None)
                elif self.path == '/api/discover':
                    result = manager.import_candidate(data.get('key'))
                elif self.path == '/api/capture':
                    config = manager.root / 'config.toml'
                    result = manager.create(data.get('name'), (manager.root / 'auth.json').read_bytes(),
                                            config.read_bytes() if config.exists() else None)
                elif self.path == '/api/preview':
                    result = manager.preview(data.get('id'), bool(data.get('archived')))
                elif self.path == '/api/backups/delete':
                    result = manager.delete_backups(data.get('ids'))
                elif self.path == '/api/color':
                    result = manager.set_color(data.get('id'), data.get('color'))
                elif self.path == '/api/details':
                    result = manager.details(data.get('id'))
                elif self.path == '/api/edit':
                    result = manager.edit(data)
                elif self.path == '/api/reveal':
                    result = manager.reveal(data.get('id'))
                elif self.path in ('/api/switch', '/api/restore', '/api/update'):
                    result = manager.start_job(self.path.split('/')[-1], data)
                elif self.path == '/api/cancel':
                    m.require(manager.job['state'] in ('waiting', 'closing'), '操作已开始，不能取消。')
                    manager.cancel.set()
                    result = {'ok': True}
                elif self.path == '/api/rename':
                    manager.ensure_ready()
                    path = manager.profile_dir(data.get('id')) / 'meta.json'
                    name = data.get('name', '').strip()
                    m.require(0 < len(name) <= 80, '请输入 1–80 字的名称。')
                    meta = m.load(path)
                    meta['name'] = name
                    m.save(path, meta)
                    result = {'ok': True}
                elif self.path == '/api/delete':
                    result = manager.delete(data.get('id'))
                elif self.path == '/api/launch':
                    result = manager.launch()
                elif self.path == '/api/maintenance/settings':
                    manager.ensure_ready()
                    result = manager.keeper.settings(data)
                elif self.path == '/api/maintenance/run':
                    result = manager.keeper.request(data.get('id'))
                elif self.path == '/api/shutdown':
                    manager.ensure_ready()
                    manager.keeper.stop.set()
                    result = {'ok': True}
                    threading.Thread(target=self.server.shutdown, daemon=True).start()
                else:
                    return self.send(404, {'error': 'Not found'})
            self.send(200, result)
        except (RuntimeError, FileNotFoundError) as exc:
            self.send(400, {'error': str(exc)})
        except Exception:
            self.send(400, {'error': '操作失败，请检查输入文件、目录权限或配置完整性。'})


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--home', type=Path, default=Path(os.environ.get('CODEX_HOME', str(Path.home() / '.codex'))))
    parser.add_argument('--port', type=int, default=8765)
    parser.add_argument('--no-browser', action='store_true')
    args = parser.parse_args()
    manager = Manager(args.home)
    from portable import file_lock
    with file_lock(manager.store / 'server.lock'):
        serve(args, manager)


def serve(args, manager):
    server = None
    for port in range(args.port, args.port + 20):
        try:
            server = ThreadingHTTPServer(('127.0.0.1', port), Handler)
            break
        except OSError:
            continue
    m.require(server is not None, '没有可用端口。')
    server.manager = manager
    server.token = secrets.token_urlsafe(32)
    server.instance = secrets.token_hex(16)
    manager.keeper.start()
    url = f'http://127.0.0.1:{server.server_port}'
    runtime_file = manager.store / 'runtime.json'
    m.save(runtime_file, {'pid': os.getpid(), 'url': url, 'instance': server.instance,
                          'csrf': server.token, 'source': str(HERE)})
    print(f'Codex Account Manager: {url}', flush=True)
    if not args.no_browser:
        webbrowser.open(url)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        manager.keeper.stop.set()
        server.server_close()
        runtime_file.unlink(missing_ok=True)


if __name__ == '__main__':
    main()
